[package]
name = "worthless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-locale = "0.2.1"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.11"